# Generated by Django 4.2.7 on 2025-09-21 18:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Poll title (5-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(200)])),
                ('description', models.TextField(blank=True, help_text='Optional poll description (max 1000 characters)', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiration date for the poll', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the poll is currently accepting votes')),
                ('allow_multiple_votes', models.BooleanField(default=False, help_text='Whether users can vote multiple times')),
                ('total_votes', models.PositiveIntegerField(db_index=True, default=0, help_text='Cached total vote count for performance')),
                ('creator', models.ForeignKey(help_text='User who created this poll', on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='Option text (1-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(200)])),
                ('vote_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Cached vote count for this option')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order of the option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll')),
            ],
            options={
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='result', serialize=False, to='polls.poll')),
                ('results_data', models.JSONField(help_text='Cached poll results in JSON format')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_votes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the voter (for anonymous vote tracking)', null=True)),
                ('voter_session', models.CharField(blank=True, help_text='Session ID for anonymous vote tracking', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll')),
                ('voter', models.ForeignKey(blank=True, help_text='User who cast the vote (null for anonymous votes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['poll', 'voter'], name='polls_vote_poll_id_6534b4_idx'), models.Index(fields=['poll', 'voter_ip'], name='polls_vote_poll_id_83027b_idx'), models.Index(fields=['poll', 'voter_session'], name='polls_vote_poll_id_93dcbd_idx'), models.Index(fields=['option', 'created_at'], name='polls_vote_option__928e75_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll', 'vote_count'], name='polls_pollo_poll_id_ebbd4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together={('poll', 'text')},
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['is_active', 'expires_at'], name='polls_poll_is_acti_5cfcc2_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['creator', 'created_at'], name='polls_poll_creator_ea8c83_idx'),
        ),
    ]
